### ISSUE TITLE
窗口小部件不自动刷新

### ISSUE THREAD

**Issue by Ju-ch** [stefanJi/dots365#1]
如题，窗口部件仅仅更新天数和百分比，点点点的个没有随着系统时间的刷新而改变。

**Comment by stefanJi** [comment]
1. 可以贴下你的手机型号和系统版本吗？ 
2. 这个问题是一直存在还是偶现的？
3. 能否贴下部分截屏？

**Comment by Ju-ch** [comment]
![Screenshot_1576823510.png](https://i.loli.net/2019/12/20/dV17wcxnjhFz9e2.png)
![Screenshot_1576823513.png](https://i.loli.net/2019/12/20/zRaS1P6xdgTOvpQ.png)

可以看到我把系统时间调整到了今年的最后一天，app内的窗口部件已经更新，但是桌面的部件却是停留在修改前的日期。
我本机是**Honor 8 Android 8.0**，不过因为我的手机系统经过很大的删改无法自定义系统时间，很难手动重现问题，所以我截了虚拟机（**Pixel 2 Android 8.0**）的图片。
我在**小米9 Android 10**上也测试过，可以相信这个问题是一直存在的。

**Comment by stefanJi** [comment]
可以试下新的 release https://github.com/stefanJi/dots365/releases/tag/release-v1.0.2

**Comment by Ju-ch** [comment]
> 可以试下新的 release https://github.com/stefanJi/dots365/releases/tag/release-v1.0.2

已经可以同步刷新了，谢谢
